CarDealership/Areas/Admin/Controllers/VehicleManagmentController.cs
using CarDealership.Services.Data.Interfaces;
using CarDealership.Web.Controllers;
using CarDealership.Web.Infrastructure;
using CarDealership.Web.ViewModels.Vehicle;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CarDealership.Web.Areas.Admin.Controllers
{
    using static Common.Constants.AdminConstants;

    [Area(AdminRoleName)]
    [Authorize(Roles = AdminRoleName)]
    public class VehicleManagmentController : BaseController
    {
        private readonly IVehicleService vehicleService;

        public VehicleManagmentController(IVehicleService vehicleService, IManagerService managerService)
            : base(managerService)
        {
            this.vehicleService = vehicleService;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] VehicleAllViewModel query)
        {


            var result = await vehicleService.Index(query.Make, query.Model, query.Type,
                query.LocatedIn, query.Category, query.Search, query.Sorting, query.CurrentPage, VehicleAllViewModel.VehicleOnPage);


            query.VehiclesCount = result.TotalVehicles;
            query.Makes = await vehicleService.AllMakeNames();
            query.Models = await vehicleService.AllModelsNames();
            query.Types = await vehicleService.AllTypesNames();
            query.Categories = await vehicleService.AllCategoriesNames();
            query.LocatedIns = await vehicleService.AllLocationsNames();
            query.Vehicles = result.Vehicles;

            return View(query);

        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Add()
        {

            var vehicle = new VehicleViewModel
            {
                VehicleCategories = await vehicleService.AllCategories(),
                VehicleTypes = await vehicleService.AllTypes(),
                VehicleLocations = await vehicleService.AllLocations(),
                VehiclePurposes = await vehicleService.AllPurposes()
            };

            return View(vehicle);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Add(VehicleViewModel vehicleViewModel)
        {
            if (await vehicleService.CaregoryExist(vehicleViewModel.CategoryId) == false)
            {
                ModelState.AddModelError(nameof(vehicleViewModel.CategoryId), "Category does not exists");
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(vehicleViewModel);
            }

            vehicleViewModel.VehicleCategories = await vehicleService.AllCategories();
            vehicleViewModel.VehicleTypes = await vehicleService.AllTypes();
            vehicleViewModel.VehicleLocations = await vehicleService.AllLocations();
            vehicleViewModel.VehiclePurposes = await vehicleService.AllPurposes();

            await this.vehicleService.AddVehicleAsync(vehicleViewModel);

            return this.RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(Guid id)
        {

            Guid vehicleGuid = Guid.Empty;
            bool isIdValid = this.IsGuidValid(id.ToString(), ref vehicleGuid);
            if (!isIdValid)
            {
                return this.RedirectToAction(nameof(Index));
            }

            bool isAdmin = User.IsInRole(AdminRoleName);

            var vehicle = await vehicleService.EditVehicleById(id, isAdmin);

            vehicle.VehicleCategories = await vehicleService.AllCategories();
            vehicle.VehicleTypes = await vehicleService.AllTypes();
            vehicle.VehicleLocations = await vehicleService.AllLocations();
            vehicle.VehiclePurposes = await vehicleService.AllPurposes();

            return View(vehicle);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(Guid id, VehicleViewModel editModel)
        {

            if (!ModelState.IsValid)
            {
                return View(editModel);
            }

            bool isAdmin = User.IsInRole(AdminRoleName);

            await vehicleService.EditVehicleAsync(editModel.Id, editModel, isAdmin);


            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            bool isAdmin = User.IsInRole(AdminRoleName);

            var deleteModel = await vehicleService.DeleteByIdAsync(id, isAdmin);

            if (deleteModel == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return this.View(deleteModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id, DeleteViewModel deleteVehicle)
        {
            bool isAdmin = User.IsInRole(AdminRoleName);

            bool isDeleted = await vehicleService
                .SoftDeleteAsync(id, isAdmin);

            if (!isDeleted)
            {
                return RedirectToAction(nameof(Delete), new { id = deleteVehicle.Id });
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CarDealership/Views/Shared/VehicleFormPartial.cshtml
@using CarDealership.Web.ViewModels.Vehicle
@model VehicleViewModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Make"></label>
                <input asp-for="Make" class="form-control" placeholder="Make...">
                <span asp-validation-for="Make" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model"></label>
                <input asp-for="Model" class="form-control" placeholder="Model...">
                <span asp-validation-for="Model" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price"></label>
                <input asp-for="Price" class="form-control" placeholder="Price...">
                <span asp-validation-for="Price" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FuelType"></label>
                <textarea asp-for="FuelType" rows="4" class="form-control" placeholder="FuelType..."></textarea>
                <span asp-validation-for="FuelType" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GearBox"></label>
                <textarea asp-for="GearBox" rows="4" class="form-control" placeholder="Gearbox..."></textarea>
                <span asp-validation-for="GearBox" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year"></label>
                <textarea asp-for="Year" rows="4" class="form-control" placeholder="Year..."></textarea>
                <span asp-validation-for="Year" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Doors"></label>
                <textarea asp-for="Doors" rows="4" class="form-control" placeholder="Doors..."></textarea>
                <span asp-validation-for="Doors" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Seats"></label>
                <textarea asp-for="Seats" rows="4" class="form-control" placeholder="Seats..."></textarea>
                <span asp-validation-for="Seats" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TankCapacity"></label>
                <textarea asp-for="TankCapacity" rows="4" class="form-control" placeholder="TankCapacity..."></textarea>
                <span asp-validation-for="TankCapacity" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HorsePower"></label>
                <textarea asp-for="HorsePower" rows="4" class="form-control" placeholder="Horsepower..."></textarea>
                <span asp-validation-for="HorsePower" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cubage"></label>
                <textarea asp-for="Cubage" rows="4" class="form-control" placeholder="Cubage..."></textarea>
                <span asp-validation-for="Cubage" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" placeholder="Your fine URL here...">
                <span asp-validation-for="ImageUrl" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId"></label>
                <select asp-for="CategoryId" class="form-control">
                    @foreach (var category in Model.VehicleCategories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeId"></label>
                <select asp-for="TypeId" class="form-control">
                    @foreach (var type in Model.VehicleTypes)
                    {
                        <option value="@type.Id">@type.Name</option>
                    }
                </select>
                <span asp-validation-for="TypeId" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LocationId"></label>
                <select asp-for="LocationId" class="form-control">
                    @foreach (var location in Model.VehicleLocations)
                    {
                        <option value="@location.Id">@location.Name</option>
                    }
                </select>
                <span asp-validation-for="LocationId" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PurposeId"></label>
                <select asp-for="PurposeId" class="form-control">
                    @foreach (var purpose in Model.VehiclePurposes)
                    {
                            <option value="@purpose.Id">@purpose.Name</option>
                    }
                </select>
                <span asp-validation-for="PurposeId" class="small text-danger"></span>
            </div>

            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

CarDealership/Views/Shared/_Messages.cshtml
@using CarDealership.Common

@if (TempData[Constants.MessageConstants.ErrorMessage] != null)
{
    <script>
        $(function () {
            toastr.error(`@TempData[Constants.MessageConstants.ErrorMessage].ToString()`);
        });
    </script>
}

@if (TempData[Constants.MessageConstants.WarningMessage] != null)
{
    <script>
        $(function () {
            toastr.warning(`@TempData[Constants.MessageConstants.WarningMessage].ToString()`);
        });
    </script>
}

@if (TempData[Constants.MessageConstants.SuccessMessage] != null)
{
    <script>
        $(function () {
            toastr.success(`@TempData[Constants.MessageConstants.SuccessMessage].ToString()`);
        });
    </script>
}

CarDealership/Views/Shared/_VehiclePartial.cshtml
@using CarDealership.Services.Data.Interfaces
@using CarDealership.Web.Infrastructure
@using CarDealership.Web.ViewModels.Vehicle
@using Microsoft.AspNetCore.Mvc.TagHelpers

@inject IManagerService ManagerService

@model VehicleServiceModel

<div class="col-md-4">
    <div class="card mb-3">
        <img class="card-img-top" src="@Model.ImageUrl" alt="Vehicle Image">
        <div class="card-body text-center">
            <h4>@Model.Make</h4>
            <h6>Модел: <b>@Model.Model</b></h6>
            <h6>
                Цена:
                <b>@String.Format("{0:f2}", Model.Price) Лева</b>
            </h6>
            <br />
            <a asp-area="" asp-controller="Vehicle" asp-action="Specifications" asp-route-id="@Model.Id"
               asp-route-information="@Model." class="btn btn-success">Specifications</a>
            @if (this.User.Identity.IsAuthenticated)
            {
                if (User.IsAdmin())
                {
                  <a asp-area="Admin" asp-controller="VehicleManagment" asp-action="Edit" asp-route-id="@Model.Id"
                     class="btn btn-warning">Edit</a>
                  <a asp-area="Admin" asp-controller="VehicleManagment" asp-action="Delete" asp-route-id="@Model.Id"
                     class="btn btn-danger">Delete</a>
                }
                @* else if (await this.ManagerService.ExistById(this.User.GetUserId()))
                {
                    <a asp-area="" asp-controller="Vehicle" asp-action="Edit" asp-route-id="@Model.Id"
                         class="btn btn-warning">Edit</a>
                } *@
            }
        </div>
    </div>
</div>